DataScientist/DataScientist/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from login_app import views

#for including static files

from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    
    url(r'^$',views.IndexView.as_view(),name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^loginhome$', views.HomeView.as_view(), name='loginhome'),
    url(r'^api/chart/data/$', views.ChartData.as_view(),name='charts'),
    url(r'^special/',views.special,name='special'),    
    url(r'^login_app/',include('login_app.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),

    url(r'^datavisualisation_app/',include('datavisualisation_app.urls',namespace='datavisualisation_app')),
]


 

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DataScientist/datavisualisation_app/urls.py
from django.conf.urls import url
from datavisualisation_app import views


# SET THE NAMESPACE!
app_name = 'datavisualisation_app'


urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home'),
    
    url(r'^api/chart/data/$', views.ChartData.as_view()),
   

]

DataScientist/login_app/urls.py
from django.conf.urls import url
from login_app import views


# SET THE NAMESPACE!
app_name = 'login_app'

urlpatterns=[
    url(r'^profile/$',views.profile,name='profile'),
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
    url(r'^loginindex/',views.loginindex,name='loginindex'),
]

DataScientist/login_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):

    # Create relationship (don't inherit from User!)
    user = models.OneToOneField(User)

    # Adding additional informations!
    # pip install pillow to use this!
    # Optional: pip install pillow --global-option=”build_ext” --global-option=”--disable-jpeg”
    sample = models.TextField(max_length=264,default='hi')
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        # Built-in attribute of django.contrib.auth.models.User !
        return self.user.username

DataScientist/login_app/forms.py
from django import forms
from django.contrib.auth.models import User
from login_app.models import UserProfileInfo



#creating forms for models

class UserForm(forms.ModelForm):
    first_name = forms.CharField(widget=forms.TextInput(
        attrs={
            'class':'form-control',
        }
    ))
    last_name = forms.CharField(widget=forms.TextInput(
        attrs={
            'class':'form-control',
        }
    ))        
    username = forms.CharField(widget=forms.TextInput(
        attrs={
            'class':'form-control',
        }
    ))
    email = forms.EmailField(widget=forms.TextInput(
        attrs={
            'class':'form-control',
        }
    ))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class':'form-control'
        }
    ))

    class Meta():
        model = User
        fields = ('first_name','last_name','username','email','password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('profile_pic',)

DataScientist/login_app/views.py
from django.shortcuts import render
from login_app.forms import UserForm,UserProfileInfoForm



# Extra Imports for the Login and Logout Capabilities
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required


from django.views.generic import View,TemplateView,ListView,DetailView,UpdateView
from . import models 


# Create your views here.
class IndexView(TemplateView):
    template_name = 'login_app/index.html'


    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['injectme'] = "Basic Injection!"
        return context
    

@login_required
def special(request):
    # Remember to also set login url in settings.py!
    # LOGIN_URL = '/basic_app/user_login/'
    return HttpResponse("You are logged in. Nice!")

@login_required
def user_logout(request):
    # Log out the user.
    logout(request)
    # Return to homepage.
    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered = False

    if request.method == 'POST':

        # Get info from "both" forms
        # It appears as one form to the user on the .html page
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        # Check to see both forms are valid
        if user_form.is_valid() and profile_form.is_valid():

            # Save User Form to Database
            user = user_form.save()

            # Hash the password
            user.set_password(user.password)

            # Update with Hashed password
            user.save()

            # Now we deal with the extra info!

            # Can't commit yet because we still need to manipulate
            profile = profile_form.save(commit=False)

            # Set One to One relationship between
            # UserForm and UserProfileInfoForm
            profile.user = user

            # Check if they provided a profile picture
            if 'profile_pic' in request.FILES:
                print('found it')
                # If yes, then grab it from the POST form reply
                profile.profile_pic = request.FILES['profile_pic']

            # Now save model
            profile.save()

            # Registration Successful!
            registered = True

        else:
            # One of the forms was invalid if this else gets called.
            print(user_form.errors,profile_form.errors)

    else:
        # Was not an HTTP post so we just render the forms as blank.
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    # This is the render and context dictionary to feed
    # back to the registration.html file page.
    return render(request,'login_app/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})

def user_login(request):

    if request.method == 'POST':
        # First get the username and password supplied
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Django's built-in authentication function:
        user = authenticate(username=username, password=password)

        # If we have a user
        if user:
            #Check it the account is active
            if user.is_active:
                # Log the user in.
                login(request,user)
                # Send the user back to some page.
                # In this case their homepage.
                return HttpResponseRedirect(reverse('login_app:loginindex'))
            else:
                # If account is not active:
                return HttpResponse("Your account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied.")

    else:
        #Nothing has been provided for username or password.
        return render(request, 'login_app/login.html', {})




def profile(request):
    return render(request,'login_app/userprofileinfo.html',{})
  


def loginindex(request):
    return render(request,'login_app/loginindex.html',{})








###########
#Data Visualisation Views
###########

from django.contrib.auth import get_user_model
from django.http import JsonResponse
from django.shortcuts import render
from django.views.generic import View

from rest_framework.views import APIView
from rest_framework.response import Response


User = get_user_model()

class HomeView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'login_app/charts.html', {"customers": 10})



def get_data(request, *args, **kwargs):
    data = {
        "sales": 100,
        "customers": 10,
    }
    return JsonResponse(data) # http response


class ChartData(APIView):
    authentication_classes = []
    permission_classes = []

    def get(self, request, format=None):
        qs_count = User.objects.all().count()
        labels = ["Users", "Blue", "Yellow", "Green", "Purple", "Orange"]
        default_items = [qs_count, 23, 2, 3, 12, 2]
        data = {
                "labels": labels,
                "default": default_items,
        }
        return Response(data)

DataScientist/templates/login_app/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
   
    <link rel="stylesheet" href="{% static 'css/footerstyles.css' %}">
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
    <script src="{% static 'js/dashboard.js' %}"></script>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">

          {# Django Home Link / Admin Link / Register Link#}
          {% if user.is_authenticated %}
          <li> <span class="btn  navbar-brand navbar-default" onclick="openNav()">&#9776;open</span></li>
          <li><a class="navbar-brand" href="{% url 'login_app:loginindex' %}">Home</a></li>
          {% else %}
          <li><a class="navbar-brand" href="{% url 'index' %}">Home</a></li>
          {% endif %}
          
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'login_app:register' %}">Register</a></li>
          


          {# Logic for login and logout option #}
          {% if user.is_authenticated %}
           <li><a href="{% url 'login_app:profile' %}">profile</a></li>
         
           <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'login_app:user_login' %}">Login</a></li>
          {% endif %}
          
        </ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>

    <div class="footer" >
      <!-- Footer -->
<footer class=" page-footer font-small blue">

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2018 Copyright:
    <a href="#"> Datascientists.com</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->
    </div>


  </body>
</html>

DataScientist/templates/login_app/charts.html
{% extends 'login_app/loginhome.html' %}

<script>
{% block jquery %}
var endpoint = '/api/chart/data/'
var defaultData = []
var labels = [];
$.ajax({
    method: "GET",
    url: endpoint,
    success: function(data){
        labels = data.labels
        defaultData = data.default
        setChart()
    },
    error: function(error_data){
        console.log("error")
        console.log(error_data)
    }
})

function setChart(){
    var ctx = document.getElementById("myChart");
    var ctx2 = document.getElementById("myChart2");
    var myChart = new Chart(ctx2, {
    type: 'bar',
    data: {
        labels: labels,
        datasets: [{
            label: '# of Votes',
            data: defaultData,
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255,99,132,1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
});

    var myChart = new Chart(ctx, {
    type: 'polarArea',
    data: {
        labels: labels,
        datasets: [{
            label: '# of Votes',
            data: defaultData,
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255,99,132,1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
});
}
// var ctx = document.getElementById("myChart");



{% endblock %}
</script>

{% block content %}

<div class='row'>
    <div class='col-sm-12' url-endpoint='{% url "api-data" %}'>
        <h1>Hello World</h1>
        <div class='col-sm-6'>
            <canvas id="myChart" width="400" height="400"></canvas>
        </div>
        <div class='col-sm-6'>
            <canvas id="myChart2" width="400" height="400"></canvas>
        </div>


    </div>
</div>

{% endblock content %}

DataScientist/templates/login_app/index.html
{% extends "login_app/base.html" %}
{% block body_block %}

<div class="container">
  <div class="jumbotron">
    <h1>Welcome to the Home Page</h1> 
        <h2>Welcome to the site!</h2>
        <h3>PLease Login</h3>
  </div>
</div>

{% endblock %}

DataScientist/templates/login_app/login.html
{% extends 'login_app/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Please Login</h1>

        <form class="form-inline" method="post" action="{% url 'login_app:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input class="form-control" type="text" name="username" placeholder="Username">
          <br>
          <label for="password">Password:</label>
          <input class="form-control" type="password" name="password">
          <br>
          <input class="btn btn-primary" type="submit" name="" value="Login">

        </form>

    </div>
  </div>
{% endblock %}

DataScientist/templates/login_app/loginhome.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">



<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">



    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js'></script>

    <title>Django + Charts.js</title>

    
  </head>
  <body>
    <div class='container'>
    {% block content %}
    {% endblock content %}
    </div>
    
    <script>
    $(document).ready(function(){
      {% block jquery %}{% endblock %}
    })
    </script>
  </body>
</html>

DataScientist/templates/login_app/loginindex.html
{% extends "login_app/base.html" %}


{% block body_block %}

<div class="container">
  <div class="jumbotron">
    <h1>Welcome to the Home Page</h1>
    {{ injectme }}
    {% if user.is_authenticated %}

        <h1>Your Dashboard</h1>
        <h1>{{ user.username }}</h1>
        
    {% else %}
        <h2>Welcome to the site! </h2>
    {% endif %}
  </div>
  {% if user.is_authenticated %}
  <div id="mySidenav" class="sidenav">
    <a href="javascript:void(0)" class="closebtn btn btn-danger" onclick="closeNav()">&times;X</a>
    <a href="#">Service 1</a>
    <a href="{% url 'datavisualisation_app:home' %}">Service 2</a>
    <a href="#">Service 3</a>
    <a href="#">Service 4</a>
  </div>
  
  <!-- Use any element to open the sidenav -->
  <!-- <span class="btn btn-primary" onclick="openNav()">&#9776;open</span> -->
  
  <!-- Add all page content inside this div if you want the side nav to push page content to the right (not used if you only want the sidenav to sit on top of the page -->

  {% endif %}
</div>

{% endblock %}

DataScientist/templates/login_app/registration.html
{% extends "login_app/base.html" %}
{% load staticfiles %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>

        <form class="form-inline"  enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>

      {% endif %}

    </div>

  </div>

{% endblock %}

DataScientist/templates/login_app/userprofileinfo.html
{% extends "login_app/base.html" %}
{% block body_block %}

{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'profilepage.css' %}">



<div class="container">
	<div class="row">
        <div class="col-lg-4" ></div>
        <div class="col-6" >
		<div class="jumbotron col-lg-3 col-sm-6">
            <div class="card hovercard">
                <div class="cardheader">

                </div>
                <div class="avatar">
                    <img class="img-circle" alt="" src="{{ user.userprofileinfo.profile_pic.url }}" height="200px" width="200px" alt="profilepic">
                </div>
                <div class="info">
                    <div class="title">
                        <h3>{{ user.username }}</h3>
                    </div>
                    <div class="desc">
                        <label for="first_name">First Name:</label>
                        <input class="form-control" type="text" value="{{ user.first_name }}" readonly>

                    </div>
                    <div class="desc">
                        <label for="last_name">Last Name:</label>
                        <input class="form-control" type="text" value="{{ user.last_name }}" readonly>                    
                    </div>
                    <div class="desc">
                        <label for="email">Email:</label>
                        <input class="form-control" type="text" value="{{ user.email }}" readonly>
                    </div>
                </div>
                <div class="bottom">
                    <a class="btn btn-primary btn-twitter btn-sm" href="#">
                        <i class="fa fa-twitter"></i>
                    </a>
                </div>
            </div>

        </div>
    </div>
    <div class="col-lg-3" ></div>
	</div>
</div>

{% endblock %}

DataScientist/templates/login_app/users.html
<!DOCTYPE html>
{% extends "login_app/base.html" %}

    {% block body_block%}
  

    <div class="container">
      <div class="jumbotron" >
          <form method="POST">
              <div class="form-group" >
                <h1>Please sign up here!</h1>
                
                  {{ form.as_p }}
                  {% csrf_token %}
                
                  <input type="submit" class='btn btn-primary' value="Submit">
               
              </div>   
            </form>
      </div>
    </div>

    



 {% endblock %}