DataScientist/DataScientist/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from login_app import views

#for including static files

from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    
    url(r'^$',views.IndexView.as_view(),name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^loginhome$', views.HomeView.as_view(), name='loginhome'),
    url(r'^api/chart/data/$', views.ChartData.as_view(),name='charts'),
    url(r'^special/',views.special,name='special'),    
    url(r'^login_app/',include('login_app.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),

    url(r'^datavisualisation_app/',include('datavisualisation_app.urls',namespace='datavisualisation_app')),
]


 

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DataScientist/datavisualisation_app/urls.py
from django.conf.urls import url
from datavisualisation_app import views


# SET THE NAMESPACE!
app_name = 'datavisualisation_app'


urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home'),
    
    url(r'^api/chart/data/$', views.ChartData.as_view()),
   

]

DataScientist/login_app/urls.py
from django.conf.urls import url
from login_app import views


# SET THE NAMESPACE!
app_name = 'login_app'

urlpatterns=[
    url(r'^profile/$',views.profile,name='profile'),
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
    url(r'^loginindex/',views.loginindex,name='loginindex'),
]

DataScientist/datavisualisation_app/models.py
from django.db import models

# Create your models here.

DataScientist/datavisualisation_app/views.py
from django.shortcuts import render

# Create your views here.
###########
#Data Visualisation Views
###########

from django.contrib.auth import get_user_model
from django.http import JsonResponse
from django.shortcuts import render
from django.views.generic import View

from rest_framework.views import APIView
from rest_framework.response import Response


User = get_user_model()

class HomeView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'datavisualisation_app/charts.html', {"customers": 10})






class ChartData(APIView):
    authentication_classes = []
    permission_classes = []

    def get(self, request, format=None):
        qs_count = User.objects.all().count()
        labels = ["Users", "Blue", "Yellow", "Green", "Purple", "Orange"]
        default_items = [qs_count, 23, 2, 3, 12, 2]
        data = {
                "labels": labels,
                "default": default_items,
        }
        return Response(data)

DataScientist/datavisualisation_app/templates/datavisualisation_app/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Django + Charts.js</title>

    {% include 'datavisualisation_app/base/css.html' %}
    {% include 'datavisualisation_app/base/bootstrap_defaults.html' %}
  </head>
  <body>



      <nav class="navbar navbar-default navbar-static-top">
          <div class="container">
            <ul class="nav navbar-nav">
    
              {# Django Home Link / Admin Link / Register Link#}
              {% if user.is_authenticated %}
              <li> <span class="btn  navbar-brand navbar-default" onclick="openNav()">&#9776;open</span></li>
              <li><a class="navbar-brand" href="{% url 'login_app:loginindex' %}">Home</a></li>
              {% else %}
              <li><a class="navbar-brand" href="{% url 'index' %}">Home</a></li>
              {% endif %}
              
              <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
              <li><a class="navbar-link" href="{% url 'login_app:register' %}">Register</a></li>
              
    
    
              {# Logic for login and logout option #}
              {% if user.is_authenticated %}
               <li><a href="{% url 'login_app:profile' %}">profile</a></li>
             
               <li><a href="{% url 'logout' %}">Logout</a></li>
              {% else %}
                <li><a class="navbar-link" href="{% url 'login_app:user_login' %}">Login</a></li>
              {% endif %}
              
            </ul>
          </div>
        </nav>
























    <div class='container'>
    {% block content %}
    {% endblock content %}
    </div>
    {% include 'datavisualisation_app/base/js.html' %}
    <script>
    $(document).ready(function(){
      {% block jquery %}
      
      {% endblock %}
    })
    </script>
  </body>
</html>

DataScientist/datavisualisation_app/templates/datavisualisation_app/charts.html
{% extends 'datavisualisation_app/base.html' %}

<script>
{% block jquery %}
var endpoint = '/api/chart/data/'
var defaultData = []
var labels = [];
$.ajax({
    method: "GET",
    url: endpoint,
    success: function(data){
        labels = data.labels
        defaultData = data.default
        setChart()
    },
    error: function(error_data){
        console.log("error")
        console.log(error_data)
    }
})

function setChart(){
    var ctx = document.getElementById("myChart");
    var ctx2 = document.getElementById("myChart2");
    var myChart = new Chart(ctx2, {
    type: 'bar',
    data: {
        labels: labels,
        datasets: [{
            label: '# of Votes',
            data: defaultData,
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255,99,132,1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
});

    var myChart = new Chart(ctx, {
    type: 'polarArea',
    data: {
        labels: labels,
        datasets: [{
            label: '# of Votes',
            data: defaultData,
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255,99,132,1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
});
}
// var ctx = document.getElementById("myChart");



{% endblock %}
</script>

{% block content %}

<div class='row'>
    
        <h1>Hello World</h1>
        <div class='col-sm-6'>
            <canvas id="myChart" width="400" height="400"></canvas>
        </div>
        <div class='col-sm-6'>
            <canvas id="myChart2" width="400" height="400"></canvas>
        </div>


    </div>
</div>

{% endblock content %}